[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Environment variables that need to be set in Railway dashboard
# MONGODB_URI - Your MongoDB connection string
# REDIS_URL - Your Redis connection string  
# OPENAI_API_KEY - Your OpenAI API key
# PORT - Railway sets this automatically 