[build]
builder = "dockerfile"

[deploy]
startCommand = "./start.sh"

# Environment variables that need to be set in Railway dashboard
# MONGODB_URI - Your MongoDB connection string
# REDIS_URL - Your Redis connection string  
# OPENAI_API_KEY - Your OpenAI API key
# PORT - Railway sets this automatically 